=== imastio/shoc/foundation/Shoc.Access/Operations/DataOps.xsd
<?xml version="1.0" encoding="utf-8"?>
<xs:schema id="DataOperations" elementFormDefault="qualified" xmlns:xs="http://www.w3.org/2001/XMLSchema">

	<!-- Root Element for Data Operations definitions -->
	<xs:element name="DataOperations">
		<xs:complexType>
			<xs:sequence>
				<xs:element ref="DataConfiguration" minOccurs="0"/>
				<xs:element ref="OperationGroup" minOccurs="0" maxOccurs="unbounded"/>
			</xs:sequence>
		</xs:complexType>

	</xs:element>

	<!-- The data configuration definition -->
	<xs:element name="DataConfiguration">
		<xs:complexType>

			<!-- Optional: Provider specific attribute values -->
			<xs:attributeGroup ref="Provider" />

			<!-- Optional: Transaction specific attribute values -->
			<xs:attributeGroup ref="Transactions" />

		</xs:complexType>

	</xs:element>

	<!-- The single group of operations -->
	<xs:element name="OperationGroup">
		<xs:complexType>

			<!-- A sequence of Sql Operations in a group -->
			<xs:sequence>
				<xs:element ref="SqlOperation" minOccurs="0" maxOccurs="unbounded" />
			</xs:sequence>

			<!-- Required: Name of the operation group -->
			<xs:attribute name="Name" use="required" />

			<!-- Optional: Provider specific attribute values -->
			<xs:attributeGroup ref="Provider" />

			<!-- Optional: Transaction specific attribute values -->
			<xs:attributeGroup ref="Transactions" />

		</xs:complexType>

	</xs:element>

	<!-- The stored procedure element definition.  -->
	<xs:element name="StoredProcedure">
		<xs:complexType>
			<xs:attributeGroup ref="BaseCommand" />
			<xs:attribute name="Name" type="xs:string" use="required" />
		</xs:complexType>
	</xs:element>

	<!-- The stored procedure element definition.  -->
	<xs:element name="TextCommand">
		<xs:complexType>
			<xs:simpleContent>
				<xs:extension base="xs:normalizedString">
					<xs:attributeGroup ref="BaseCommand" />
				</xs:extension>
			</xs:simpleContent>
		</xs:complexType>
	</xs:element>

	<!-- A single Sql Operation Definition -->
	<xs:element name="SqlOperation">
		<xs:complexType>

			<!-- Child Elements of Sql Operation -->
			<xs:choice>

				<!-- A reference to stored procedure definition  -->
				<xs:element ref="StoredProcedure" />

				<!-- A reference to text-based command definition  -->
				<xs:element ref="TextCommand" />

			</xs:choice>

			<!-- Required: Name of the Sql Operation -->
			<xs:attribute name="Name" type="xs:string" use="required" />

			<!-- Optional: Provider specific attribute values -->
			<xs:attributeGroup ref="Provider" />

			<!-- Optional: Transaction specific attribute values -->
			<xs:attributeGroup ref="Transactions" />

		</xs:complexType>
	</xs:element>

	<!-- Provider-related attributes for operation groups and operations -->
	<xs:attributeGroup name="Provider">
		<!-- Optional: Provider of the Sql Operation -->
		<xs:attribute name="Compatibility" type="CompatibilityProviders" />

		<!-- Optional: Timeout value for the operation -->
		<xs:attribute name="Timeout" type="xs:duration" />
	</xs:attributeGroup>

	<!-- Command-specific common attributes  -->
	<xs:attributeGroup name="BaseCommand">
		<xs:attribute name="ExpectedResult" type="ExpectedResultOptions" default="Unknown" />
	</xs:attributeGroup>

	<!-- Transaction-related attributes for operation groups and operations -->
	<xs:attributeGroup name="Transactions">
		<!-- Optional: Transactional behavior of operation -->
		<xs:attribute name="AutoTransaction" type="AutoTransactionMode" />

	</xs:attributeGroup>

	<!-- The options of expected results -->
	<xs:simpleType name="ExpectedResultOptions" final="restriction" >
		<xs:restriction base="xs:string">
			<xs:enumeration value="Unknown" />
			<xs:enumeration value="Table" />
			<xs:enumeration value="MultipleTables" />
			<xs:enumeration value="Scalar" />
			<xs:enumeration value="RowCount" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Define if an Operation or Operation Group should be wrapped into a transaction -->
	<xs:simpleType name="Transactional" final="restriction" >
		<xs:restriction base="xs:string">
			<xs:enumeration value="Yes" />
			<xs:enumeration value="No" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Define what should transaction isolation level be for Operation or Operation Group -->
	<xs:simpleType name="AutoTransactionMode" final="restriction" >
		<xs:restriction base="xs:string">
			<xs:enumeration value="No" />
			<xs:enumeration value="RepeatableRead" />
			<xs:enumeration value="ReadUncommitted" />
			<xs:enumeration value="ReadCommitted" />
			<xs:enumeration value="Serializable" />
		</xs:restriction>
	</xs:simpleType>

	<!-- Define supported providers for the Operation or an Operation group -->
	<xs:simpleType name="CompatibilityProviders" final="list" >
		<xs:list>
			<xs:simpleType>
				<xs:restriction base="xs:string">
					<xs:enumeration value="SqlServer" />
					<xs:enumeration value="MySQL" />
					<xs:enumeration value="PostgreSQL" />
					<xs:enumeration value="SQLite" />
					<xs:enumeration value="Any" />
					<xs:enumeration value="None" />
				</xs:restriction>
			</xs:simpleType>
		</xs:list>

	</xs:simpleType>

</xs:schema>

=== imastio/shoc/apps/shoc-identity/Shoc.Identity.Provider/Operations/Identity.OidcProvider.xml
<?xml version="1.0" encoding="utf-8" ?>

<DataOperations xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="DataOps.xsd">

    <!-- The configuration applies to any operation in this file. Using global timeout for 5 minutes -->
    <DataConfiguration Timeout="PT5M" AutoTransaction="RepeatableRead" Compatibility="MySQL"/>

    <OperationGroup Name="Identity.OidcProvider">

        <SqlOperation Name="GetAll">
            <TextCommand>
                SELECT *
                FROM `idp_oidc_providers`
                ORDER BY Created DESC;
            </TextCommand>
        </SqlOperation>

        <SqlOperation Name="GetById">
            <TextCommand>
                SELECT *
                FROM `idp_oidc_providers` 
                WHERE `Id` = @Id;
            </TextCommand>
        </SqlOperation>

        <SqlOperation Name="GetByCode">
            <TextCommand>
                SELECT *
                FROM `idp_oidc_providers`
                WHERE `Code` = @Code;
            </TextCommand>
        </SqlOperation>

        <SqlOperation Name="Create">

            <TextCommand>
                INSERT INTO `idp_oidc_providers`
                (`Id`, `Code`, `Type`, `Name`, `IconUrl`, `Authority`, `ResponseType`, `ClientId`, `ClientSecretEncrypted`, `Scope`, `FetchUserInfo`, `Pkce`, `Disabled`, `Trusted`)
                VALUES
                (@Id, @Code, @Type, @Name, @IconUrl, @Authority, @ResponseType, @ClientId, @ClientSecretEncrypted, @Scope, @FetchUserInfo, @Pkce, @Disabled, @Trusted);

                SELECT *
                FROM `idp_oidc_providers` WHERE `Id` = @Id;
            </TextCommand>

        </SqlOperation>
                
        <SqlOperation Name="UpdateById">

            <TextCommand>
                UPDATE `idp_oidc_providers`
                SET
                `Code` = @Code,
                `Type` = @Type,
                `Name` = @Name,
                `IconUrl` = @IconUrl,
                `Authority` = @Authority,
                `ResponseType` = @ResponseType,
                `ClientId` = @ClientId,
                `Scope` = @Scope,
                `FetchUserInfo` = @FetchUserInfo,
                `Pkce` = @Pkce,
                `Disabled` = @Disabled,
                `Trusted` = @Trusted
                WHERE `Id` = @Id;

                SELECT *
                FROM `idp_oidc_providers` WHERE `Id` = @Id;
            </TextCommand>

        </SqlOperation>

        <SqlOperation Name="UpdateClientSecretById">

            <TextCommand>
                UPDATE `idp_oidc_providers`
                SET
                `ClientSecretEncrypted` = @ClientSecretEncrypted
                WHERE `Id` = @Id;

                SELECT *
                FROM `idp_oidc_providers` WHERE `Id` = @Id;
            </TextCommand>

        </SqlOperation>

        <SqlOperation Name="DeleteById">

            <TextCommand>
                SELECT *
                FROM `idp_oidc_providers` 
                WHERE `Id` = @Id;

                DELETE FROM `idp_oidc_providers` WHERE `Id` = @Id;
            </TextCommand>

        </SqlOperation>

    </OperationGroup>

</DataOperations>

=== imastio/shoc/apps/shoc-identity/Shoc.Identity.Provider/Operations/Identity.OidcProvider.Domain.xml
<?xml version="1.0" encoding="utf-8" ?>

<DataOperations xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="DataOps.xsd">

    <!-- The configuration applies to any operation in this file. Using global timeout for 5 minutes -->
    <DataConfiguration Timeout="PT5M" AutoTransaction="RepeatableRead" Compatibility="MySQL"/>

    <OperationGroup Name="Identity.OidcProvider.Domain">

        <SqlOperation Name="GetAll">
            <TextCommand>
                SELECT *
                FROM `idp_oidc_provider_domains`
                WHERE `ProviderId` = @ProviderId
                ORDER BY Created DESC;
            </TextCommand>
        </SqlOperation>

        <SqlOperation Name="GetById">
            <TextCommand>
                SELECT *
                FROM `idp_oidc_provider_domains` 
                WHERE `ProviderId` = @ProviderId AND `Id` = @Id;
            </TextCommand>
        </SqlOperation>

        <SqlOperation Name="GetByDomainName">
            <TextCommand>
                SELECT *
                FROM `idp_oidc_provider_domains`
                WHERE `ProviderId` = @ProviderId AND `DomainName` = @DomainName;
            </TextCommand>
        </SqlOperation>
        
        <SqlOperation Name="Create">

            <TextCommand>
                INSERT INTO `idp_oidc_provider_domains`
                (`Id`, `ProviderId`, `DomainName`, `Verified`)
                VALUES
                (@Id, @ProviderId, @DomainName, @Verified);

                SELECT *
                FROM `idp_oidc_provider_domains` WHERE `ProviderId` = @ProviderId AND `Id` = @Id;
            </TextCommand>

        </SqlOperation>
                
        <SqlOperation Name="UpdateById">

            <TextCommand>
                UPDATE `idp_oidc_provider_domains`
                SET
                `DomainName` = @DomainName,
                `Verified` = @Verified
                WHERE `ProviderId` = @ProviderId AND `Id` = @Id;

                SELECT *
                FROM `idp_oidc_provider_domains` WHERE `ProviderId` = @ProviderId AND `Id` = @Id;
            </TextCommand>

        </SqlOperation>

        <SqlOperation Name="DeleteById">

            <TextCommand>
                SELECT *
                FROM `idp_oidc_provider_domains` 
                WHERE `ProviderId` = @ProviderId AND `Id` = @Id;

                DELETE FROM `idp_oidc_provider_domains` WHERE `ProviderId` = @ProviderId AND `Id` = @Id;
            </TextCommand>

        </SqlOperation>

    </OperationGroup>

</DataOperations>

=== imastio/shoc/apps/shoc-job/Shoc.Job.Data.Sql/Operations/Job.Task.xml
<?xml version="1.0" encoding="utf-8" ?>

<DataOperations xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="DataOps.xsd">

  <!-- The configuration applies to any operation in this file. Using global timeout for 5 minutes -->
  <DataConfiguration Timeout="PT5M" AutoTransaction="RepeatableRead" Compatibility="MySQL"/>

  <OperationGroup Name="Job.Task">

    <SqlOperation Name="GetAll">
      <TextCommand>
        SELECT * FROM `job_job_tasks`
        WHERE `WorkspaceId` = @WorkspaceId AND `JobId` = @JobId
        ORDER BY Sequence ASC;
      </TextCommand>
    </SqlOperation>

    <SqlOperation Name="GetAllExtended">
      <TextCommand>
        SELECT j.*, w.Name as WorkspaceName, u.FullName as UserFullName, c.Name as ClusterName, p.Image as PackageImage
        FROM `job_job_tasks` j
        INNER JOIN `wspc_workspaces` w
        ON j.WorkspaceId = w.Id
        INNER JOIN `idp_users` u
        ON j.UserId = u.Id
        INNER JOIN `clstr_clusters` c
        ON j.ClusterId = c.Id
        INNER JOIN `pkg_packages` p
        ON j.PackageId = p.Id
        WHERE j.`WorkspaceId` = @WorkspaceId AND j.`JobId` = @JobId
        ORDER BY j.Sequence ASC;
      </TextCommand>
    </SqlOperation>
    
    <SqlOperation Name="GetById">
      <TextCommand>
        SELECT * FROM `job_job_tasks`
        WHERE `WorkspaceId` = @WorkspaceId AND `JobId` = @JobId AND `Id` = @Id;
      </TextCommand>
    </SqlOperation>

    <SqlOperation Name="GetExtendedById">
      <TextCommand>
        SELECT j.*, w.Name as WorkspaceName, u.FullName as UserFullName, c.Name as ClusterName, p.Image as PackageImage
        FROM `job_job_tasks` j
        INNER JOIN `wspc_workspaces` w
        ON j.WorkspaceId = w.Id
        INNER JOIN `idp_users` u
        ON j.UserId = u.Id
        INNER JOIN `clstr_clusters` c
        ON j.ClusterId = c.Id
        INNER JOIN `pkg_packages` p
        ON j.PackageId = p.Id
        WHERE j.`WorkspaceId` = @WorkspaceId AND j.`JobId` = @JobId AND j.`Id` = @Id;
      </TextCommand>
    </SqlOperation>

  </OperationGroup>

</DataOperations>

=== imastio/shoc/apps/shoc-cluster/Shoc.Cluster.Data.Sql/Operations/Cluster.xml
<?xml version="1.0" encoding="utf-8" ?>

<DataOperations xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="DataOps.xsd">

  <!-- The configuration applies to any operation in this file. Using global timeout for 5 minutes -->
  <DataConfiguration Timeout="PT5M" AutoTransaction="RepeatableRead" Compatibility="MySQL"/>

  <OperationGroup Name="Cluster">

    <SqlOperation Name="GetAll">
      <TextCommand>
        SELECT * FROM `clstr_clusters`
        WHERE 1=1
        {if:ByWorkspace {and `WorkspaceId` = @WorkspaceId} else {}}
        ORDER BY `Updated` DESC;
      </TextCommand>
    </SqlOperation>

    <SqlOperation Name="GetAllExtended">
      <TextCommand>
        SELECT c.*, w.Name as WorkspaceName 
        FROM 
          `clstr_clusters` c
        INNER JOIN
          `wspc_workspaces` w
        ON c.WorkspaceId = w.Id
        WHERE 1=1
        {if:ByWorkspace {and c.`WorkspaceId` = @WorkspaceId} else {}}
        ORDER BY c.`Updated` DESC;
      </TextCommand>
    </SqlOperation>

    <SqlOperation Name="GetAllReferentialValues">
      <TextCommand>
        SELECT `Id`, `WorkspaceId`, `Name`, `Type`, `Status`
        FROM `clstr_clusters`
        WHERE `WorkspaceId` = @WorkspaceId
        ORDER BY `Name` ASC;
      </TextCommand>
    </SqlOperation>
    
    <SqlOperation Name="GetById">
      <TextCommand>
        SELECT * FROM `clstr_clusters`
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;
      </TextCommand>
    </SqlOperation>

    <SqlOperation Name="GetExtendedById">
      <TextCommand>
        SELECT c.*, w.Name as WorkspaceName
        FROM
        `clstr_clusters` c
        INNER JOIN
        `wspc_workspaces` w
        ON c.WorkspaceId = w.Id
        WHERE c.`WorkspaceId` = @WorkspaceId AND c.`Id` = @Id;
      </TextCommand>
    </SqlOperation>
    
    <SqlOperation Name="GetByName">
      <TextCommand>
        SELECT * FROM `clstr_clusters`
        WHERE `WorkspaceId` = @WorkspaceId AND `Name` = @Name;
      </TextCommand>
    </SqlOperation>

    <SqlOperation Name="GetExtendedByName">
      <TextCommand>
        SELECT c.*, w.Name as WorkspaceName
        FROM
        `clstr_clusters` c
        INNER JOIN
        `wspc_workspaces` w
        ON c.WorkspaceId = w.Id
        WHERE c.`WorkspaceId` = @WorkspaceId AND c.`Name` = @Name;
      </TextCommand>
    </SqlOperation>

    <SqlOperation Name="CountAll">
      <TextCommand>
        SELECT COUNT(Id) as Count FROM `clstr_clusters`
        WHERE `WorkspaceId` = @WorkspaceId;
      </TextCommand>
    </SqlOperation>

    <SqlOperation Name="Create">

      <TextCommand>
        INSERT INTO `clstr_clusters`
        (`Id`, `WorkspaceId`, `Name`, `Description`, `Type`, `Status`, `Configuration`)
        VALUES
        (@Id, @WorkspaceId, @Name, @Description, @Type, @Status, @Configuration);

        SELECT * FROM `clstr_clusters`
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;
      </TextCommand>

    </SqlOperation>

    <SqlOperation Name="UpdateById">
      <TextCommand>
        UPDATE `clstr_clusters`
        SET
        `Name` = @Name,
        `Description` = @Description,
        `Type` = @Type,
        `Status` = @Status
        WHERE
        `WorkspaceId` = @WorkspaceId AND `Id` = @Id;

        SELECT * FROM `clstr_clusters`
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;

      </TextCommand>
    </SqlOperation>

    <SqlOperation Name="UpdateConfigurationById">
      <TextCommand>
        UPDATE `clstr_clusters`
        SET
        `Configuration` = @Configuration
        WHERE
        `WorkspaceId` = @WorkspaceId AND `Id` = @Id;

        SELECT * FROM `clstr_clusters`
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;

      </TextCommand>
    </SqlOperation>
    
    <SqlOperation Name="DeleteById">
      <TextCommand>
        SELECT * FROM `clstr_clusters` WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;
        DELETE FROM `clstr_clusters` WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;
      </TextCommand>
    </SqlOperation>

  </OperationGroup>

</DataOperations>

=== imastio/shoc/apps/shoc-job/Shoc.Job.Data.Sql/Operations/Job.xml
<?xml version="1.0" encoding="utf-8" ?>

<DataOperations xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="DataOps.xsd">

  <!-- The configuration applies to any operation in this file. Using global timeout for 5 minutes -->
  <DataConfiguration Timeout="PT5M" AutoTransaction="RepeatableRead" Compatibility="MySQL"/>

  <OperationGroup Name="Job">

    <SqlOperation Name="GetAll">
      <TextCommand>
        SELECT * FROM `job_jobs`
        WHERE `WorkspaceId` = @WorkspaceId
        ORDER BY `LocalId` Asc;
      </TextCommand>
    </SqlOperation>

    <SqlOperation Name="GetById">
      <TextCommand>
        SELECT * FROM `job_jobs`
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;
      </TextCommand>
    </SqlOperation>

    <SqlOperation Name="GetTasksById">
      <TextCommand>
        SELECT * FROM `job_job_tasks`
        WHERE `WorkspaceId` = @WorkspaceId AND `JobId` = @Id;
      </TextCommand>
    </SqlOperation>
    
    <SqlOperation Name="Create" AutoTransaction="No">

      <TextCommand>

        SET @nextLocalId = (
          SELECT COALESCE(MAX(LocalId), 0) + 1
          FROM job_jobs
          WHERE `WorkspaceId` = @WorkspaceId
        );
        
        INSERT INTO `job_jobs`
        (`Id`, `WorkspaceId`, `LocalId`, `ClusterId`, `UserId`, `Scope`, `Manifest`, `ClusterConfigEncrypted`, `Namespace`, 
        `TotalTasks`, `SucceededTasks`, `FailedTasks`, `CancelledTasks`, `CompletedTasks`, `Status`, `Message`, `PendingAt`, `RunningAt`, `CompletedAt`)
        VALUES
        (@Id, @WorkspaceId, @nextLocalId, @ClusterId, @UserId, @Scope, @Manifest, @ClusterConfigEncrypted, @Namespace,
        @TotalTasks, @SucceededTasks, @FailedTasks, @CancelledTasks, @CompletedTasks, @Status, @Message, @PendingAt, @RunningAt, @CompletedAt);

        SELECT * FROM `job_jobs`
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;
      </TextCommand>

    </SqlOperation>

    <SqlOperation Name="CreateTask" AutoTransaction="No">

      <TextCommand>

        INSERT INTO `job_job_tasks`
        (`Id`, `WorkspaceId`, `JobId`, `Sequence`, `ClusterId`, `PackageId`, `UserId`, `Type`, `Runtime`, `Args`, `PackageReferenceEncrypted`,
        `ArrayReplicas`, `ArrayIndexer`, `ArrayCounter`, `ResolvedEnvEncrypted`, `MemoryRequested`, `CpuRequested`, `NvidiaGpuRequested`, 
        `AmdGpuRequested`, `Spec`, `Status`, `Message`, `PendingAt`, `RunningAt`, `CompletedAt`)
        VALUES
        (@Id, @WorkspaceId, @JobId, @Sequence, @ClusterId, @PackageId, @UserId, @Type, @Runtime, @Args, @PackageReferenceEncrypted,
        @ArrayReplicas, @ArrayIndexer, @ArrayCounter, @ResolvedEnvEncrypted, @MemoryRequested, @CpuRequested, @NvidiaGpuRequested,
        @AmdGpuRequested, @Spec, @Status, @Message, @PendingAt, @RunningAt, @CompletedAt);
        
      </TextCommand>

    </SqlOperation>

    <SqlOperation Name="CreateLabel" AutoTransaction="No">

      <TextCommand>

        INSERT INTO `job_job_labels`
        (`Id`, `WorkspaceId`, `JobId`, `LabelId`)
        VALUES
        (@Id, @WorkspaceId, @JobId, @LabelId)
        ON DUPLICATE KEY UPDATE `LabelId` = @LabelId; 
        
      </TextCommand>

    </SqlOperation>

    <SqlOperation Name="CreateGitRepo" AutoTransaction="No">

      <TextCommand>

        INSERT INTO `job_job_git_repositories`
        (`Id`, `WorkspaceId`, `JobId`, `GitRepoId`)
        VALUES
        (@Id, @WorkspaceId, @JobId, @GitRepoId)
        ON DUPLICATE KEY UPDATE `GitRepoId` = @GitRepoId;

      </TextCommand>

    </SqlOperation>

    <SqlOperation Name="UpdateNamespaceById" AutoTransaction="No">

      <TextCommand>
        UPDATE `job_jobs`
        SET
          `Namespace` = @Namespace
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;
        
        SELECT * FROM `job_jobs`
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;
      </TextCommand>

    </SqlOperation>

    <SqlOperation Name="FailById">

      <TextCommand>
        UPDATE `job_jobs`
        SET
        `Message` = @Message,
        `CompletedAt` = @CompletedAt,
        `Status` = @Status,
        `SucceededTasks` = 0,
        `CancelledTasks` = 0,
        `FailedTasks` = `TotalTasks`,
        `CompletedTasks` = `TotalTasks`
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;

        UPDATE `job_job_tasks`
        SET
        `Status` = @TaskStatus,
        `CompletedAt` = @CompletedAt,
        `Message` = @Message
        WHERE `WorkspaceId` = @WorkspaceId AND `JobId` = @Id;
        
        SELECT * FROM `job_jobs`
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;
      </TextCommand>

    </SqlOperation>

    <SqlOperation Name="DeleteById">
      <TextCommand>
        SELECT * FROM `job_jobs` WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;
        DELETE FROM `job_jobs` WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @Id;
      </TextCommand>
    </SqlOperation>
    
  </OperationGroup>

</DataOperations>

=== imastio/shoc/apps/shoc-job/Shoc.Job.Data.Sql/Operations/Job.TaskStatus.xml
<?xml version="1.0" encoding="utf-8" ?>

<DataOperations xmlns="" xmlns:xsi="http://www.w3.org/2001/XMLSchema-instance"
                xsi:noNamespaceSchemaLocation="DataOps.xsd">

  <!-- The configuration applies to any operation in this file. Using global timeout for 5 minutes -->
  <DataConfiguration Timeout="PT5M" AutoTransaction="RepeatableRead" Compatibility="MySQL"/>

  <OperationGroup Name="Job.TaskStatus">

    
    <SqlOperation Name="SubmitTaskById">

      <TextCommand>
        UPDATE `job_job_tasks`
        SET
        `Status` = @PendingTaskStatus,
        `PendingAt` = @PendingAt,
        `Message` = @Message
        WHERE `WorkspaceId` = @WorkspaceId AND `JobId` = @JobId AND `Id` = @Id;

        UPDATE `job_jobs`
        SET
        `Status` = @PendingJobStatus,
        `PendingAt` = @PendingAt
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @JobId AND `Status` IN @TargetJobStatuses;

        SELECT * FROM `job_job_tasks`
        WHERE `WorkspaceId` = @WorkspaceId AND `JobId` = @JobId AND `Id` = @Id;
      </TextCommand>

    </SqlOperation>

    <SqlOperation Name="RunningTaskById">

      <TextCommand>
        UPDATE `job_job_tasks`
        SET
        `Status` = @RunningTaskStatus,
        `RunningAt` = @RunningAt,
        `Message` = @Message
        WHERE `WorkspaceId` = @WorkspaceId AND `JobId` = @JobId AND `Id` = @Id;

        UPDATE `job_jobs`
        SET
        `Status` = @RunningJobStatus,
        `RunningAt` = @RunningAt
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @JobId AND `Status` IN @TargetJobStatuses;

        SELECT * FROM `job_job_tasks`
        WHERE `WorkspaceId` = @WorkspaceId AND `JobId` = @JobId AND `Id` = @Id;
      </TextCommand>

    </SqlOperation>

    <SqlOperation Name="CompleteTaskById">

      <TextCommand>
        UPDATE `job_job_tasks`
        SET
        `Status` = @Status,
        `CompletedAt` = @CompletedAt,
        `Message` = @Message
        WHERE `WorkspaceId` = @WorkspaceId AND `JobId` = @JobId AND `Id` = @Id;

        UPDATE `job_jobs`
        SET
        `SucceededTasks` = `SucceededTasks` + @SucceededTaskIncrement,
        `FailedTasks` = `FailedTasks` + @FailedTaskIncrement,
        `CancelledTasks` = `CancelledTasks` + @CancelledTaskIncrement,
        `CompletedTasks` = `CompletedTasks` + 1
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @JobId;

        UPDATE `job_jobs`
        SET 
        `CompletedAt` = CASE
          WHEN `CompletedTasks` = `TotalTasks` THEN @CompletedAt
          ELSE `CompletedAt`
        END,
        `Status` = CASE
          WHEN `SucceededTasks` = `TotalTasks` THEN @SucceededJobStatus
          WHEN `FailedTasks` = `TotalTasks` THEN @FailedJobStatus
          WHEN `CancelledTasks` = `TotalTasks` THEN @CancelledJobStatus
          WHEN `CompletedTasks` = `TotalTasks` AND `SucceededTasks` > 0 THEN @PartiallySucceededJobStatus
          ELSE `Status`
          END
        WHERE `WorkspaceId` = @WorkspaceId AND `Id` = @JobId;
        
        SELECT * FROM `job_job_tasks`
        WHERE `WorkspaceId` = @WorkspaceId AND `JobId` = @JobId AND `Id` = @Id;
      </TextCommand>

    </SqlOperation>

  </OperationGroup>

</DataOperations>
